source 'https://github.com/CocoaPods/Specs.git'

target 'RgWsPublicClient', :exclusive => true do
  pod "RgWsPublicClient", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "RgWsPublicClient", :path => "../"

  
end
